name: CD
name: CD
on:
  push:
    branches:
      - main

  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: "3.9"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set Up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: package-${{ matrix.python-version }}
          path: dist/

      - name: Install poetry
        run: |
          make install-poetry
          poetry config virtualenvs.create false
      - name: Install dependencies
        run: |
          make install
      - name: Check publishing the package
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN_TEST }}
          PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "action@github.com"
          semantic-release publish -D commit_author="github-actions <action@github.com>"
