name: CI/CD
on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Run in all these versions of Python
        python-version: ["3.8", "3.9", "3.10"]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set Up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install poetry
        run: |
          pip install poetry==1.1.14
      - name: Install dependencies
        run: |
          make install
      - name: Run tests with pytest
        run: |
          make test
      - name: Build the package
        run: |
          make build
      - uses: actions/upload-artifact@master
        with:
          name: package-${{ matrix.python-version }}
          path: dist/

  publish:
    needs: [build]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    # if: github.ref == 'refs/heads/main'
    # if: github.event_name == 'push' && github.ref == 'refs/heads/main' && !contains(github.event.head_commit.message, 'chore(release):')
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: package-${{ matrix.python-version }}
          path: dist/
      - name: Install poetry
        run: |
          pip install poetry==1.1.14
      - name: Check publishing the package
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN_TEST }}
          PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
        run: |
          make check-publish
      - name: Publish the package
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN_TEST }}
          PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
        run: |
          make publish
