name: Run code checks
on: [push]
jobs:
  checks:
    name: Run code checks
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install poetry
        run: |
          pip install poetry
      - name: Install dependencies
        run: |
          make install
      - name: Run checks
        run: |
          make check-all
